2025-01-30 11:05:51.183  INFO 12912 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 12912 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 11:05:51.187 DEBUG 12912 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 11:05:51.188  INFO 12912 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 11:05:51.699  INFO 12912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 11:05:51.701  INFO 12912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 11:05:51.723  INFO 12912 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 11:05:52.087  INFO 12912 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 11:05:52.094  INFO 12912 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 11:05:52.095  INFO 12912 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 11:05:52.155  INFO 12912 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 11:05:52.155  INFO 12912 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 937 ms
2025-01-30 11:05:53.643  INFO 12912 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 11:05:54.107  INFO 12912 --- [redisson-netty-4-29] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 11:05:54.332  INFO 12912 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 11:05:54.480  INFO 12912 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 11:05:54.669  INFO 12912 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 11:05:54.676  INFO 12912 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.798 seconds (JVM running for 4.426)
2025-01-30 11:06:48.063  INFO 12912 --- [http-nio-8081-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 11:06:48.063  INFO 12912 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 11:06:48.067  INFO 12912 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
2025-01-30 11:06:48.428  INFO 12912 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 11:06:48.915  INFO 12912 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 11:06:48.920 DEBUG 12912 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==>  Preparing: SELECT id,name,icon,sort,create_time,update_time FROM tb_shop_type
2025-01-30 11:06:48.931 DEBUG 12912 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==> Parameters: 
2025-01-30 11:06:48.973 DEBUG 12912 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : <==      Total: 10
2025-01-30 11:06:51.872 DEBUG 12912 --- [http-nio-8081-exec-3] com.hsj.hmdp.service.IUserServiceImpl    : 验证码成功生成，为：877171
2025-01-30 11:06:55.900 DEBUG 12912 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==>  Preparing: SELECT id,phone,password,nick_name,icon,create_time,update_time FROM tb_user WHERE (phone = ?)
2025-01-30 11:06:55.901 DEBUG 12912 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==> Parameters: 18050285529(String)
2025-01-30 11:06:55.938 DEBUG 12912 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : <==      Total: 1
2025-01-30 11:09:31.543 DEBUG 12912 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.VoucherMapper.insert    : ==>  Preparing: INSERT INTO tb_voucher ( shop_id, title, sub_title, rules, pay_value, actual_value, type, create_time, update_time ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ? )
2025-01-30 11:09:31.544 DEBUG 12912 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.VoucherMapper.insert    : ==> Parameters: 1(Long), 1200元代金券(String), 周一至周五均可使用(String), YZDL可用(String), 8000(Long), 10000(Long), 1(Integer), 2025-01-30T11:09:31.543(LocalDateTime), 2025-01-30T11:09:31.543(LocalDateTime)
2025-01-30 11:09:31.606 DEBUG 12912 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.VoucherMapper.insert    : <==    Updates: 1
2025-01-30 11:09:31.611 DEBUG 12912 --- [http-nio-8081-exec-6] c.h.h.dao.SeckillVoucherMapper.insert    : ==>  Preparing: INSERT INTO tb_seckill_voucher ( voucher_id, stock, create_time, begin_time, end_time, update_time ) VALUES ( ?, ?, ?, ?, ?, ? )
2025-01-30 11:09:31.613 DEBUG 12912 --- [http-nio-8081-exec-6] c.h.h.dao.SeckillVoucherMapper.insert    : ==> Parameters: 11(Long), 100(Integer), 2025-01-30T11:09:31.611(LocalDateTime), 2024-11-26T10:09:17(LocalDateTime), 2026-03-26T23:09:04(LocalDateTime), 2025-01-30T11:09:31.611(LocalDateTime)
2025-01-30 11:09:31.682 DEBUG 12912 --- [http-nio-8081-exec-6] c.h.h.dao.SeckillVoucherMapper.insert    : <==    Updates: 1
2025-01-30 11:11:43.013  INFO 12912 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 11:11:43.102  INFO 12912 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 11:11:43.106  INFO 12912 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 11:54:48.411  INFO 22788 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 22788 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 11:54:48.413 DEBUG 22788 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 11:54:48.413  INFO 22788 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 11:54:48.798  INFO 22788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 11:54:48.799  INFO 22788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 11:54:48.816  INFO 22788 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 11:54:49.112  INFO 22788 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 11:54:49.118  INFO 22788 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 11:54:49.118  INFO 22788 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 11:54:49.171  INFO 22788 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 11:54:49.172  INFO 22788 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 736 ms
2025-01-30 11:54:50.465  INFO 22788 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 11:54:50.900  INFO 22788 --- [redisson-netty-4-26] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 11:54:51.114  INFO 22788 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 11:54:51.229  INFO 22788 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 11:54:51.392  INFO 22788 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 11:54:51.399  INFO 22788 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.219 seconds (JVM running for 3.795)
2025-01-30 11:54:56.434  INFO 22788 --- [http-nio-8081-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 11:54:56.434  INFO 22788 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 11:54:56.439  INFO 22788 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2025-01-30 11:54:56.843  INFO 22788 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 11:54:57.355  INFO 22788 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 11:54:57.359 DEBUG 22788 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==>  Preparing: SELECT id,name,icon,sort,create_time,update_time FROM tb_shop_type
2025-01-30 11:54:57.369 DEBUG 22788 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==> Parameters: 
2025-01-30 11:54:57.422 DEBUG 22788 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : <==      Total: 10
2025-01-30 11:54:58.858 DEBUG 22788 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 11:54:58.859 DEBUG 22788 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 11:54:58.906 DEBUG 22788 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 11:54:59.662 DEBUG 22788 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 11:54:59.663 DEBUG 22788 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 11:54:59.702 DEBUG 22788 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 11:54:59.731 DEBUG 22788 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.ShopMapper.selectById   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE id=?
2025-01-30 11:54:59.733 DEBUG 22788 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.ShopMapper.selectById   : ==> Parameters: 1(Long)
2025-01-30 11:54:59.765 DEBUG 22788 --- [http-nio-8081-exec-6] com.hsj.hmdp.dao.ShopMapper.selectById   : <==      Total: 1
2025-01-30 11:55:03.836 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.SeckillVoucherMapper.selectById  : ==>  Preparing: SELECT voucher_id,stock,create_time,begin_time,end_time,update_time FROM tb_seckill_voucher WHERE voucher_id=?
2025-01-30 11:55:03.837 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.SeckillVoucherMapper.selectById  : ==> Parameters: 10(Long)
2025-01-30 11:55:03.873 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.SeckillVoucherMapper.selectById  : <==      Total: 1
2025-01-30 11:55:03.970 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.VoucherOrderMapper.selectCount   : ==>  Preparing: SELECT COUNT( * ) FROM tb_voucher_order WHERE (user_id = ? AND voucher_id = ?)
2025-01-30 11:55:03.971 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.VoucherOrderMapper.selectCount   : ==> Parameters: 1016(Long), 10(Long)
2025-01-30 11:55:04.010 DEBUG 22788 --- [http-nio-8081-exec-7] c.h.h.d.VoucherOrderMapper.selectCount   : <==      Total: 1
2025-01-30 11:55:11.971 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.SeckillVoucherMapper.selectById  : ==>  Preparing: SELECT voucher_id,stock,create_time,begin_time,end_time,update_time FROM tb_seckill_voucher WHERE voucher_id=?
2025-01-30 11:55:11.972 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.SeckillVoucherMapper.selectById  : ==> Parameters: 11(Long)
2025-01-30 11:55:12.006 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.SeckillVoucherMapper.selectById  : <==      Total: 1
2025-01-30 11:55:12.084 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.selectCount   : ==>  Preparing: SELECT COUNT( * ) FROM tb_voucher_order WHERE (user_id = ? AND voucher_id = ?)
2025-01-30 11:55:12.084 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.selectCount   : ==> Parameters: 1016(Long), 11(Long)
2025-01-30 11:55:12.124 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.selectCount   : <==      Total: 1
2025-01-30 11:55:12.125 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.stock_minus   : ==>  Preparing: UPDATE tb_seckill_voucher SET stock = stock- 1 WHERE voucher_id = ? AND stock > 0
2025-01-30 11:55:12.125 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.stock_minus   : ==> Parameters: 11(Long)
2025-01-30 11:55:12.203 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.h.d.VoucherOrderMapper.stock_minus   : <==    Updates: 1
2025-01-30 11:55:12.241 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.hmdp.dao.VoucherOrderMapper.insert   : ==>  Preparing: INSERT INTO tb_voucher_order ( id, user_id, voucher_id, create_time, update_time ) VALUES ( ?, ?, ?, ?, ? )
2025-01-30 11:55:12.242 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.hmdp.dao.VoucherOrderMapper.insert   : ==> Parameters: 688918389275492353(Long), 1016(Long), 11(Long), 2025-01-30T11:55:12.241(LocalDateTime), 2025-01-30T11:55:12.241(LocalDateTime)
2025-01-30 11:55:12.314 DEBUG 22788 --- [http-nio-8081-exec-8] c.h.hmdp.dao.VoucherOrderMapper.insert   : <==    Updates: 1
2025-01-30 11:55:18.804  INFO 22788 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 11:55:18.880  INFO 22788 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 11:55:18.883  INFO 22788 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 16:42:52.643  INFO 10488 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 10488 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 16:42:52.645 DEBUG 10488 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 16:42:52.645  INFO 10488 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 16:42:53.057  INFO 10488 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 16:42:53.058  INFO 10488 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 16:42:53.074  INFO 10488 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8ms. Found 0 Redis repository interfaces.
2025-01-30 16:42:53.374  INFO 10488 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 16:42:53.380  INFO 10488 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 16:42:53.380  INFO 10488 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 16:42:53.432  INFO 10488 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 16:42:53.432  INFO 10488 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 760 ms
2025-01-30 16:42:54.779  INFO 10488 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 16:42:55.219  INFO 10488 --- [redisson-netty-4-13] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 16:42:55.481  INFO 10488 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 16:42:55.607  INFO 10488 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 16:42:55.776  INFO 10488 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 16:42:55.782  INFO 10488 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.382 seconds (JVM running for 3.964)
2025-01-30 16:43:06.447  INFO 10488 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 16:43:06.447  INFO 10488 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 16:43:06.452  INFO 10488 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2025-01-30 16:43:06.810  INFO 10488 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 16:43:07.381  INFO 10488 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 16:43:07.388 DEBUG 10488 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==>  Preparing: SELECT id,name,icon,sort,create_time,update_time FROM tb_shop_type
2025-01-30 16:43:07.402 DEBUG 10488 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==> Parameters: 
2025-01-30 16:43:07.456 DEBUG 10488 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : <==      Total: 10
2025-01-30 16:43:14.717 DEBUG 10488 --- [http-nio-8081-exec-4] com.hsj.hmdp.service.IUserServiceImpl    : 验证码成功生成，为：126942
2025-01-30 16:43:20.450 DEBUG 10488 --- [http-nio-8081-exec-3] com.hsj.hmdp.dao.UserMapper.selectOne    : ==>  Preparing: SELECT id,phone,password,nick_name,icon,create_time,update_time FROM tb_user WHERE (phone = ?)
2025-01-30 16:43:20.450 DEBUG 10488 --- [http-nio-8081-exec-3] com.hsj.hmdp.dao.UserMapper.selectOne    : ==> Parameters: 18050285529(String)
2025-01-30 16:43:20.494 DEBUG 10488 --- [http-nio-8081-exec-3] com.hsj.hmdp.dao.UserMapper.selectOne    : <==      Total: 1
2025-01-30 16:44:54.318 DEBUG 10488 --- [http-nio-8081-exec-9] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 16:44:54.319 DEBUG 10488 --- [http-nio-8081-exec-9] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 16:44:54.363 DEBUG 10488 --- [http-nio-8081-exec-9] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 16:44:55.333 DEBUG 10488 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 16:44:55.334 DEBUG 10488 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 16:44:55.385 DEBUG 10488 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 16:44:55.422 DEBUG 10488 --- [http-nio-8081-exec-10] com.hsj.hmdp.dao.ShopMapper.selectById   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE id=?
2025-01-30 16:44:55.422 DEBUG 10488 --- [http-nio-8081-exec-10] com.hsj.hmdp.dao.ShopMapper.selectById   : ==> Parameters: 1(Long)
2025-01-30 16:44:55.463 DEBUG 10488 --- [http-nio-8081-exec-10] com.hsj.hmdp.dao.ShopMapper.selectById   : <==      Total: 1
2025-01-30 16:44:59.855 ERROR 10488 --- [http-nio-8081-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR Unknown Redis command called from script script: 6c7c80c43c74e46a98ef451b7dabe2c493e20ded, on @user_script:28.] with root cause

io.lettuce.core.RedisCommandExecutionException: ERR Unknown Redis command called from script script: 6c7c80c43c74e46a98ef451b7dabe2c493e20ded, on @user_script:28.
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:47:27.452  INFO 10488 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 16:47:27.537  INFO 10488 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 16:47:27.541  INFO 10488 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 16:47:29.625  INFO 9124 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 9124 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 16:47:29.627 DEBUG 9124 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 16:47:29.627  INFO 9124 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 16:47:30.014  INFO 9124 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 16:47:30.016  INFO 9124 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 16:47:30.032  INFO 9124 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 16:47:30.329  INFO 9124 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 16:47:30.335  INFO 9124 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 16:47:30.335  INFO 9124 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 16:47:30.386  INFO 9124 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 16:47:30.387  INFO 9124 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 735 ms
2025-01-30 16:47:31.768  INFO 9124 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 16:47:32.247  INFO 9124 --- [redisson-netty-4-14] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 16:47:33.209  INFO 9124 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 16:47:33.338  INFO 9124 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 16:47:33.503  INFO 9124 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 16:47:33.510  INFO 9124 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 4.117 seconds (JVM running for 4.709)
2025-01-30 16:47:45.590  INFO 9124 --- [http-nio-8081-exec-3] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 16:47:45.590  INFO 9124 --- [http-nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 16:47:45.597  INFO 9124 --- [http-nio-8081-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2025-01-30 16:47:45.955  INFO 9124 --- [http-nio-8081-exec-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 16:47:46.493  INFO 9124 --- [http-nio-8081-exec-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 16:47:46.498 DEBUG 9124 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 16:47:46.509 DEBUG 9124 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 16:47:46.558 DEBUG 9124 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 16:48:34.852  WARN 9124 --- [http-nio-8081-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:48:36.592  WARN 9124 --- [http-nio-8081-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:48:37.587  WARN 9124 --- [http-nio-8081-exec-8] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:48:37.752  WARN 9124 --- [http-nio-8081-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:48:37.899  WARN 9124 --- [http-nio-8081-exec-7] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:52:11.841  INFO 9124 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 16:52:11.930  INFO 9124 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 16:52:11.934  INFO 9124 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 16:52:19.312  INFO 1868 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 1868 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 16:52:19.314 DEBUG 1868 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 16:52:19.314  INFO 1868 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 16:52:19.707  INFO 1868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 16:52:19.708  INFO 1868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 16:52:19.725  INFO 1868 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 16:52:20.017  INFO 1868 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 16:52:20.024  INFO 1868 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 16:52:20.025  INFO 1868 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 16:52:20.074  INFO 1868 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 16:52:20.075  INFO 1868 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 736 ms
2025-01-30 16:52:21.356  INFO 1868 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 16:52:21.829  INFO 1868 --- [redisson-netty-4-14] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 16:52:22.091  INFO 1868 --- [redisson-netty-4-18] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 16:52:22.214  INFO 1868 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 16:52:22.380  INFO 1868 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 16:52:22.387  INFO 1868 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.318 seconds (JVM running for 3.889)
2025-01-30 16:52:30.044  INFO 1868 --- [http-nio-8081-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 16:52:30.045  INFO 1868 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 16:52:30.050  INFO 1868 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2025-01-30 16:52:33.401 DEBUG 1868 --- [http-nio-8081-exec-3] com.hsj.hmdp.service.IUserServiceImpl    : 验证码成功生成，为：395208
2025-01-30 16:52:41.224  INFO 1868 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 16:52:41.743  INFO 1868 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 16:52:41.747 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==>  Preparing: SELECT id,phone,password,nick_name,icon,create_time,update_time FROM tb_user WHERE (phone = ?)
2025-01-30 16:52:41.757 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==> Parameters: 18050285529(String)
2025-01-30 16:52:41.803 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : <==      Total: 1
2025-01-30 16:53:26.316  WARN 1868 --- [http-nio-8081-exec-8] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:55:07.580 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 16:55:07.580 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 16:55:07.624 DEBUG 1868 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 16:57:05.180  WARN 1868 --- [http-nio-8081-exec-10] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-6] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x475a51a1, L:/192.168.245.54:52196 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-3] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xeacdd9e0, L:/192.168.245.54:52201 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-12] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xf67c54a0, L:/192.168.245.54:52205 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-9] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xf22ddbcf, L:/192.168.245.54:52198 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-4] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x75eb98c7, L:/192.168.245.54:52199 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-11] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x0fe3aeef, L:/192.168.245.54:52197 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-2] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xb92914c6, L:/192.168.245.54:52195 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-7] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x9764e96f, L:/192.168.245.54:52204 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-10] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x9ae1e5af, L:/192.168.245.54:52203 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-8] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xdfce7401, L:/192.168.245.54:52202 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.491 ERROR 1868 --- [redisson-netty-4-5] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x1c9b589f, L:/192.168.245.54:52200 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-16] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xcf373e13, L:/192.168.245.54:52207 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-31] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xd2b51538, L:/192.168.245.54:52213 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-1] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xe7638601, L:/192.168.245.54:52212 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-28] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x1dd9e064, L:/192.168.245.54:52211 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-30] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xd63b874a, L:/192.168.245.54:52214 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.561 ERROR 1868 --- [redisson-netty-4-17] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xce25e6de, L:/192.168.245.54:52208 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.577 ERROR 1868 --- [redisson-netty-4-27] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x49936415, L:/192.168.245.54:52210 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.577 ERROR 1868 --- [redisson-netty-4-32] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x3e7d904a, L:/192.168.245.54:52216 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.577 ERROR 1868 --- [redisson-netty-4-26] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xf6e5773c, L:/192.168.245.54:52209 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.577 ERROR 1868 --- [redisson-netty-4-29] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x28486890, L:/192.168.245.54:52215 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.656 ERROR 1868 --- [redisson-netty-4-8] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x57db501b, L:/192.168.245.54:52219 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.656 ERROR 1868 --- [redisson-netty-4-5] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0xea832a80, L:/192.168.245.54:52218 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.656 ERROR 1868 --- [redisson-netty-4-9] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x13f673bf, L:/192.168.245.54:52220 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:42.671 ERROR 1868 --- [redisson-netty-4-4] o.r.client.handler.ErrorsLoggingHandler  : Exception occured. Channel: [id: 0x4213711d, L:/192.168.245.54:52217 - R:/121.40.226.231:6379]

java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[na:1.8.0_152]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_152]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_152]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.338 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf22ddbcf, L:/192.168.245.54:52198 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x0fe3aeef, L:/192.168.245.54:52197 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf67c54a0, L:/192.168.245.54:52205 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x9764e96f, L:/192.168.245.54:52204 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x1c9b589f, L:/192.168.245.54:52200 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xb92914c6, L:/192.168.245.54:52195 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x75eb98c7, L:/192.168.245.54:52199 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xdfce7401, L:/192.168.245.54:52202 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x9ae1e5af, L:/192.168.245.54:52203 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.339 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xeacdd9e0, L:/192.168.245.54:52201 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.341 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x475a51a1, L:/192.168.245.54:52196 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.432 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xce25e6de, L:/192.168.245.54:52208 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.432 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xcf373e13, L:/192.168.245.54:52207 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.432 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x1dd9e064, L:/192.168.245.54:52211 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.432 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xe7638601, L:/192.168.245.54:52212 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.432 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xd2b51538, L:/192.168.245.54:52213 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.433 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x28486890, L:/192.168.245.54:52215 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.433 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xd63b874a, L:/192.168.245.54:52214 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.433 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x49936415, L:/192.168.245.54:52210 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.433 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x3e7d904a, L:/192.168.245.54:52216 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.433 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xf6e5773c, L:/192.168.245.54:52209 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.528 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x4213711d, L:/192.168.245.54:52217 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.528 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x57db501b, L:/192.168.245.54:52219 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.528 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0xea832a80, L:/192.168.245.54:52218 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 16:59:53.528 ERROR 1868 --- [redisson-timer-6-1] o.r.c.handler.PingConnectionHandler      : Unable to send PING command over channel: [id: 0x13f673bf, L:/192.168.245.54:52220 ! R:/121.40.226.231:6379]

org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING), params: [], Redis client: [addr=redis://121.40.226.231:6379]
	at org.redisson.client.RedisConnection.lambda$async$1(RedisConnection.java:207) ~[redisson-3.13.6.jar:3.13.6]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:669) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:744) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:469) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 17:02:58.269 ERROR 1868 --- [http-nio-8081-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 6 second(s)] with root cause

io.lettuce.core.RedisCommandTimeoutException: Command timed out after 6 second(s)
	at io.lettuce.core.internal.ExceptionFactory.createTimeoutException(ExceptionFactory.java:59) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.internal.Futures.awaitOrCancel(Futures.java:246) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:74) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1061) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.lambda$doInvoke$4(LettuceConnection.java:920) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$Synchronizer.invoke(LettuceInvoker.java:665) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker.just(LettuceInvoker.java:94) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.lettuce.LettuceHashCommands.hGetAll(LettuceHashCommands.java:126) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.hGetAll(DefaultedRedisConnection.java:1366) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.hGetAll(DefaultStringRedisConnection.java:549) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.core.DefaultHashOperations.lambda$entries$18(DefaultHashOperations.java:307) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:223) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:307) ~[spring-data-redis-2.6.2.jar:2.6.2]
	at com.hsj.hmdp.utils.RefreshTokenInterceptor.preHandle(RefreshTokenInterceptor.java:30) ~[classes/:na]
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:151) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_152]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 17:03:13.947  INFO 1868 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 17:03:14.055  INFO 1868 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 17:03:14.060  INFO 1868 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 17:03:17.967  INFO 2976 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 2976 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 17:03:17.969 DEBUG 2976 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 17:03:17.969  INFO 2976 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 17:03:18.371  INFO 2976 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 17:03:18.372  INFO 2976 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 17:03:18.387  INFO 2976 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8ms. Found 0 Redis repository interfaces.
2025-01-30 17:03:18.681  INFO 2976 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 17:03:18.686  INFO 2976 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 17:03:18.686  INFO 2976 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 17:03:18.735  INFO 2976 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 17:03:18.735  INFO 2976 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 742 ms
2025-01-30 17:03:20.020  INFO 2976 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 17:03:20.497  INFO 2976 --- [redisson-netty-4-16] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 17:03:20.740  INFO 2976 --- [redisson-netty-4-18] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 17:03:20.862  INFO 2976 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 17:03:21.031  INFO 2976 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 17:03:21.037  INFO 2976 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.303 seconds (JVM running for 3.932)
2025-01-30 17:03:25.962  INFO 2976 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 17:03:25.962  INFO 2976 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 17:03:25.966  INFO 2976 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2025-01-30 17:04:06.305  WARN 2976 --- [http-nio-8081-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2025-01-30 17:05:13.073  INFO 2976 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 17:05:16.157  INFO 4696 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 4696 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 17:05:16.160 DEBUG 4696 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 17:05:16.160  INFO 4696 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 17:05:16.552  INFO 4696 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 17:05:16.553  INFO 4696 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 17:05:16.570  INFO 4696 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 17:05:16.876  INFO 4696 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 17:05:16.882  INFO 4696 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 17:05:16.882  INFO 4696 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 17:05:16.933  INFO 4696 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 17:05:16.933  INFO 4696 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 749 ms
2025-01-30 17:05:18.256  INFO 4696 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 17:05:18.723  INFO 4696 --- [redisson-netty-4-26] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 17:05:18.965  INFO 4696 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 17:05:19.097  INFO 4696 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 17:05:19.272  INFO 4696 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 17:05:19.278  INFO 4696 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.356 seconds (JVM running for 3.918)
2025-01-30 17:05:30.244  INFO 4696 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 17:05:30.244  INFO 4696 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 17:05:30.248  INFO 4696 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2025-01-30 17:05:37.195 DEBUG 4696 --- [http-nio-8081-exec-2] com.hsj.hmdp.service.IUserServiceImpl    : 验证码成功生成，为：440169
2025-01-30 17:05:42.760  INFO 4696 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 17:05:43.300  INFO 4696 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 17:05:43.304 DEBUG 4696 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==>  Preparing: SELECT id,phone,password,nick_name,icon,create_time,update_time FROM tb_user WHERE (phone = ?)
2025-01-30 17:05:43.314 DEBUG 4696 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : ==> Parameters: 18050285529(String)
2025-01-30 17:05:43.368 DEBUG 4696 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.UserMapper.selectOne    : <==      Total: 1
2025-01-30 17:06:42.709 DEBUG 4696 --- [http-nio-8081-exec-2] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 17:06:42.709 DEBUG 4696 --- [http-nio-8081-exec-2] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 17:06:42.756 DEBUG 4696 --- [http-nio-8081-exec-2] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 17:06:43.773 DEBUG 4696 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 17:06:43.774 DEBUG 4696 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 17:06:43.819 DEBUG 4696 --- [http-nio-8081-exec-5] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 17:11:52.212  INFO 4696 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 17:11:52.308  INFO 4696 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 17:11:52.312  INFO 4696 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 18:00:08.881  INFO 22892 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 22892 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 18:00:08.882 DEBUG 22892 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 18:00:08.883  INFO 22892 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 18:00:09.288  INFO 22892 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 18:00:09.289  INFO 22892 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 18:00:09.306  INFO 22892 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 18:00:09.607  INFO 22892 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 18:00:09.613  INFO 22892 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 18:00:09.613  INFO 22892 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 18:00:09.664  INFO 22892 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 18:00:09.664  INFO 22892 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 755 ms
2025-01-30 18:00:10.988  INFO 22892 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 18:00:11.436  INFO 22892 --- [redisson-netty-4-32] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 18:00:11.677  INFO 22892 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 18:00:11.806  INFO 22892 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 18:00:11.970  INFO 22892 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 18:00:11.977  INFO 22892 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.34 seconds (JVM running for 4.065)
2025-01-30 18:00:51.067  INFO 22892 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 18:00:51.067  INFO 22892 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 18:00:51.073  INFO 22892 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2025-01-30 18:00:51.498  INFO 22892 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 18:00:52.032  INFO 22892 --- [http-nio-8081-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 18:00:52.036 DEBUG 22892 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==>  Preparing: SELECT id,name,icon,sort,create_time,update_time FROM tb_shop_type
2025-01-30 18:00:52.048 DEBUG 22892 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : ==> Parameters: 
2025-01-30 18:00:52.095 DEBUG 22892 --- [http-nio-8081-exec-1] c.h.hmdp.dao.ShopTypeMapper.selectList   : <==      Total: 10
2025-01-30 18:00:53.985 DEBUG 22892 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 18:00:53.986 DEBUG 22892 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 18:00:54.026 DEBUG 22892 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 18:00:54.938 DEBUG 22892 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 18:00:54.939 DEBUG 22892 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 18:00:55.058 DEBUG 22892 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 18:00:55.106 DEBUG 22892 --- [http-nio-8081-exec-5] com.hsj.hmdp.dao.ShopMapper.selectById   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE id=?
2025-01-30 18:00:55.107 DEBUG 22892 --- [http-nio-8081-exec-5] com.hsj.hmdp.dao.ShopMapper.selectById   : ==> Parameters: 1(Long)
2025-01-30 18:00:55.144 DEBUG 22892 --- [http-nio-8081-exec-5] com.hsj.hmdp.dao.ShopMapper.selectById   : <==      Total: 1
2025-01-30 18:00:56.461 ERROR 22892 --- [http-nio-8081-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR user_script:15: attempt to compare nil with number script: 523e265662097248a589c565577ed637657ab3c8, on @user_script:15.] with root cause

io.lettuce.core.RedisCommandExecutionException: ERR user_script:15: attempt to compare nil with number script: 523e265662097248a589c565577ed637657ab3c8, on @user_script:15.
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 18:03:45.170  INFO 22892 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 18:03:45.226  INFO 22892 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 18:03:45.229  INFO 22892 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 18:03:49.566  INFO 23656 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 23656 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 18:03:49.568 DEBUG 23656 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 18:03:49.568  INFO 23656 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 18:03:49.984  INFO 23656 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 18:03:49.985  INFO 23656 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 18:03:50.002  INFO 23656 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 18:03:50.324  INFO 23656 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 18:03:50.329  INFO 23656 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 18:03:50.330  INFO 23656 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 18:03:50.386  INFO 23656 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 18:03:50.386  INFO 23656 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 789 ms
2025-01-30 18:03:51.717  INFO 23656 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 18:03:52.205  INFO 23656 --- [redisson-netty-4-17] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 18:03:52.452  INFO 23656 --- [redisson-netty-4-18] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 18:03:52.598  INFO 23656 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 18:03:52.786  INFO 23656 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 18:03:52.794  INFO 23656 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.478 seconds (JVM running for 4.079)
2025-01-30 18:03:57.614  INFO 23656 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 18:03:57.614  INFO 23656 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 18:03:57.618  INFO 23656 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2025-01-30 18:03:58.956  INFO 23656 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 18:03:59.488  INFO 23656 --- [http-nio-8081-exec-4] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 18:03:59.494 DEBUG 23656 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==>  Preparing: SELECT id,name,type_id,images,area,address,x,y,avg_price,sold,comments,score,open_hours,create_time,update_time FROM tb_shop WHERE (type_id = ?)
2025-01-30 18:03:59.510 DEBUG 23656 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : ==> Parameters: 1(Integer)
2025-01-30 18:03:59.560 DEBUG 23656 --- [http-nio-8081-exec-4] com.hsj.hmdp.dao.ShopMapper.selectPage   : <==      Total: 9
2025-01-30 18:04:00.446 DEBUG 23656 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 18:04:00.448 DEBUG 23656 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 18:04:00.495 DEBUG 23656 --- [http-nio-8081-exec-6] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 18:04:03.465 ERROR 23656 --- [http-nio-8081-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR user_script:15: attempt to compare nil with number script: 523e265662097248a589c565577ed637657ab3c8, on @user_script:15.] with root cause

io.lettuce.core.RedisCommandExecutionException: ERR user_script:15: attempt to compare nil with number script: 523e265662097248a589c565577ed637657ab3c8, on @user_script:15.
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:147) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:116) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]

2025-01-30 18:06:06.007  INFO 23656 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 18:06:06.109  INFO 23656 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 18:06:06.112  INFO 23656 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 18:06:10.194  INFO 21016 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 21016 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 18:06:10.196 DEBUG 21016 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 18:06:10.196  INFO 21016 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 18:06:10.596  INFO 21016 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 18:06:10.597  INFO 21016 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 18:06:10.616  INFO 21016 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 10ms. Found 0 Redis repository interfaces.
2025-01-30 18:06:10.916  INFO 21016 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 18:06:10.920  INFO 21016 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 18:06:10.921  INFO 21016 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 18:06:10.973  INFO 21016 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 18:06:10.973  INFO 21016 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 753 ms
2025-01-30 18:06:12.278  INFO 21016 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 18:06:12.719  INFO 21016 --- [redisson-netty-4-24] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 18:06:12.954  INFO 21016 --- [redisson-netty-4-19] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 18:06:13.087  INFO 21016 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 18:06:13.254  INFO 21016 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 18:06:13.261  INFO 21016 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.314 seconds (JVM running for 3.871)
2025-01-30 18:06:17.741  INFO 21016 --- [http-nio-8081-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 18:06:17.741  INFO 21016 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 18:06:17.747  INFO 21016 --- [http-nio-8081-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2025-01-30 18:06:18.125  INFO 21016 --- [http-nio-8081-exec-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 18:06:18.661  INFO 21016 --- [http-nio-8081-exec-2] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 18:06:18.666 DEBUG 21016 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 18:06:18.678 DEBUG 21016 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 18:06:18.744 DEBUG 21016 --- [http-nio-8081-exec-2] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 18:08:26.521  INFO 21016 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 18:08:26.627  INFO 21016 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 18:08:26.631  INFO 21016 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2025-01-30 18:08:32.215  INFO 20456 --- [main] com.hsj.hmdp.HmdpApplication             : Starting HmdpApplication on DESKTOP-JFH821A with PID 20456 (E:\hmdp\my_heima_dianping\target\classes started by ZhuanZ in E:\hmdp\my_heima_dianping)
2025-01-30 18:08:32.217 DEBUG 20456 --- [main] com.hsj.hmdp.HmdpApplication             : Running with Spring Boot v2.3.12.RELEASE, Spring v5.2.15.RELEASE
2025-01-30 18:08:32.217  INFO 20456 --- [main] com.hsj.hmdp.HmdpApplication             : No active profile set, falling back to default profiles: default
2025-01-30 18:08:32.687  INFO 20456 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2025-01-30 18:08:32.689  INFO 20456 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2025-01-30 18:08:32.706  INFO 20456 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 9ms. Found 0 Redis repository interfaces.
2025-01-30 18:08:33.032  INFO 20456 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8081 (http)
2025-01-30 18:08:33.038  INFO 20456 --- [main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-01-30 18:08:33.038  INFO 20456 --- [main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
2025-01-30 18:08:33.093  INFO 20456 --- [main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-01-30 18:08:33.094  INFO 20456 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 850 ms
2025-01-30 18:08:34.498  INFO 20456 --- [main] org.redisson.Version                     : Redisson 3.13.6
2025-01-30 18:08:34.971  INFO 20456 --- [redisson-netty-4-23] o.r.c.pool.MasterPubSubConnectionPool    : 1 connections initialized for /121.40.226.231:6379
2025-01-30 18:08:35.239  INFO 20456 --- [redisson-netty-4-18] o.r.c.pool.MasterConnectionPool          : 24 connections initialized for /121.40.226.231:6379
2025-01-30 18:08:35.409  INFO 20456 --- [main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2025-01-30 18:08:35.607  INFO 20456 --- [main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8081 (http) with context path ''
2025-01-30 18:08:35.617  INFO 20456 --- [main] com.hsj.hmdp.HmdpApplication             : Started HmdpApplication in 3.664 seconds (JVM running for 4.295)
2025-01-30 18:08:39.982  INFO 20456 --- [http-nio-8081-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-01-30 18:08:39.982  INFO 20456 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-01-30 18:08:39.986  INFO 20456 --- [http-nio-8081-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2025-01-30 18:08:40.370  INFO 20456 --- [http-nio-8081-exec-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-01-30 18:08:40.914  INFO 20456 --- [http-nio-8081-exec-3] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-01-30 18:08:40.919 DEBUG 20456 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : ==>  Preparing: SELECT v.`id`, v.`shop_id`, v.`title`, v.`sub_title`, v.`rules`, v.`pay_value`, v.`actual_value`, v.`type`, sv.`stock` , COALESCE(sv.begin_time, NOW()) AS begin_time, COALESCE(sv.end_time, DATE_ADD(NOW(), INTERVAL 1 DAY)) AS end_time FROM tb_voucher v LEFT JOIN tb_seckill_voucher sv ON v.id = sv.voucher_id WHERE v.shop_id = ? AND v.status = 1
2025-01-30 18:08:40.929 DEBUG 20456 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : ==> Parameters: 1(Long)
2025-01-30 18:08:40.986 DEBUG 20456 --- [http-nio-8081-exec-3] c.h.h.d.V.queryVoucherOfShop             : <==      Total: 3
2025-01-30 18:08:42.361 DEBUG 20456 --- [pool-2-thread-1] c.h.hmdp.dao.VoucherOrderMapper.insert   : ==>  Preparing: INSERT INTO tb_voucher_order ( id, user_id, voucher_id, create_time, update_time ) VALUES ( ?, ?, ?, ?, ? )
2025-01-30 18:08:42.363 DEBUG 20456 --- [pool-2-thread-1] c.h.hmdp.dao.VoucherOrderMapper.insert   : ==> Parameters: 689014639492595717(Long), 1016(Long), 10(Long), 2025-01-30T18:08:42.318(LocalDateTime), 2025-01-30T18:08:42.318(LocalDateTime)
2025-01-30 18:08:42.449 DEBUG 20456 --- [pool-2-thread-1] c.h.hmdp.dao.VoucherOrderMapper.insert   : <==    Updates: 1
2025-01-30 18:08:58.514  INFO 20456 --- [SpringContextShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2025-01-30 18:08:58.588  INFO 20456 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2025-01-30 18:08:58.591  INFO 20456 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
